version: '2'
services:
    web:
        build: .
        command: python -u app.py
        volumes:
            - .:/juno
        network_mode: 'host'
        environment:
            - MAIL_USER=${MAIL_USER}
            - MAIL_PASSWORD=${MAIL_PASSWORD}
